export const LOGIN_USER_START = 'LOGIN_USER_START'
export const LOGIN_USER_REQUEST = 'LOGIN_USER_REQUEST'
export const LOGIN_USER_FAILURE = 'LOGIN_USER_FAILURE'
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS'
export const LOGOUT_USER = 'LOGOUT_USER'

export const GET_BALANCE = 'GET_BALANCE'
export const MAKE_DEPOSIT = 'MAKE_DEPOSIT'
export const WITHDRAW_DEPOSIT = 'WITHDRAW_DEPOSIT'
